import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./lib/providers";
import { Toaster } from 'sonner'
import { Footer, Navbar } from "./components/common";
import NextTopLoader from 'nextjs-toploader';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Novaschool",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="" >
            <body className={inter.className}>
                <Providers>
                    <NextTopLoader
                        color="#000"
                        showSpinner={false}
                     />
                    <Toaster richColors />
                    <main className="flex min-h-screen flex-col bg-[#111111] ">
                        <div className="bg-white rounded-[0_0_20px_20px] md:rounded-[0_0_40px_40px] lg:rounded-[0_0_80px_80px] relative">
                            <Navbar />
                            {children}
                        </div>
                        <Footer />
                    </main>
                </Providers>
            </body>
        </html>
    );
}
